
@startuml

class pygame.sprite.Sprite{
    ...
}

class Player1{
    +pygame.sprite.Sprite.__init__()
    +velx: float
    +vely: float
    +angle: float
    +engine: str
    +fuel: float
    +points: int
    +rocket1image: pygame imageload
    +rocket2image: pygame imageload
    +rect.center: tuple
    +fuelinfo_x: int
    +fuelinfo_y: int
    +pointsinfo_x: int
    +pointsinfo_y0: int
    +rect: pygamerect

    +reset()
    +controls(bullet_sprites)
    +image_direction()
    +update(collide, bullet_sprites)
}


class Player2{
    +Player1.__init__()
    +rect.center: tuple
    +fuelinfo_x: int
    +fuelinfo_y: int
    +pointsinfo_x: int
    +pointsinfo_y: int

    +reset()
    +controls(bullet_sprites)

}



class Bullets{
    +Player1.__init__(self)
    +velx:float
    +vely:float
    +rect: pygamerect
    +fuel_amount:float
    +image: pyload image
    +rect.midtop: tuple

    +update()
}

class Fuelbarrel{
        +fuel_amount: float
        +image: pyload image
        +rect: pygamerect
        +rect.center: tuple

        +pygame.sprite.Sprite.__init__()

}

class Wall{
        +image: pygame_rect
        +image.fill((WHITE))
        +rect: pygamerect
        +rect.center: tuple

        +pygame.sprite.Sprite.__init__()
}


class Game{
        +self.gameloop(): init
        +gameloop()
        +point_assigner_win(group, player_sprites)
        +point_assigner_loss(group, player_sprites):
        +background(Background)
}


pygame.sprite.Sprite <-- Player1
Player1 <-- Player2
pygame.sprite.Sprite <-- Bullets
pygame.sprite.Sprite <-- Fuelbarrel
pygame.sprite.Sprite <-- Wall

@enduml